###
GET http://localhost:4000/posts?limit=10&page=1
###

POST http://localhost:4000/signup
Content-Type: application/json

{
    "username":"user1",
    "password":"password1"
}
###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username":"user1",
    "password":"password"
}
